### ISSUE TITLE
Scroll is bugged when in a TabView

### ISSUE THREAD

**Issue by florianmari** [izakpavel/SwiftUIPagingScrollView#1]
Hey,

Your work is amazing! But there's a issue when you run from a TabView the scroll is broken I didn't check why yet!

**Comment by izakpavel** [comment]
Hey, thanks for the message, I will check that ;)

so 21. 9. 2019 v 15:47 odesílatel Florian Mari <notifications@github.com>
napsal:

**Comment by izakpavel** [comment]
Damn, took me a while to get back to it, but the TabView issue is now resolved
